name: bayes-binary 
program: task_3_1_sweep_bayes.py
project: training-bayes-sweeps
entity: jonaspeschel-technical-university-of-berlin
method: grid
metric:
  goal: maximize
  name: test_weighted_f1
parameters:
  # pre-processing
  only_binary:
    value: true
  remove_punct:
    value: false
  remove_stopwords:
    value: false
  remove_nums:
    value: true 
  lemmatize:
    value: true
  # text vectorization
  vectorization:
    value: BagOfWords
