name: network-binary
program: task_3_2_sweep_nn.py
project: training-nn-sweeps
# entity: jonaspeschel-technical-university-of-berlin
entity: jonaspeschel
method: grid 
# run_cap: 50
metric:
  goal: maximize
  name: test_weighted_f1
parameters:
  # pre-processing
  only_binary:
    value: true
  remove_punct:
    value: false
  remove_stopwords:
    value: false
  remove_nums:
    value: false 
  lemmatize:
    value: true
  # text vectorization
  vectorization:
    value: BagOfWords
  # network training
  learning_rate:
    value: !!float 1e-4
  l1_reg: 
    value: !!float 1e-5
  l2_reg: 
    value: !!float 1e-4
  n_epochs:
    value: 100
  batch_size:
    value: 16
  hidden_layer_dim:
    value: 10