name: train-nn-sweep
program: task_3_2_sweep_nn.py
project: training-nn-sweeps
entity: jonaspeschel-technical-university-of-berlin
method: random
run_cap: 1
metric:
  goal: maximize
  name: test_weighted_f1
parameters:
  # pre-processing
  only_binary:
    value: false
  remove_punct:
    values: [true, false]
  remove_stopwords:
    values: [true, false]
  remove_nums:
    values: [true, false]
  lemmatize:
    values: [true, false]
  # text vectorization
  vectorization:
    values: ["BagOfWords", "TF-IDF"]
    # values: ["Glove-50", "Glove-200"]
  # network training
  learning_rate:
    min: !!float 1e-5
    max: !!float 1e-2
  l1_reg: 
    value: !!float 1e-5
  l2_reg: 
    value: !!float 1e-4
  n_epochs:
    values: [20, 35, 50]
  batch_size:
    values: [16, 32, 64]
  hidden_layer_dim:
    values: [2, 5, 10]
    # values: [32, 64, 128]